# This is a basic workflow to help you get started with Actions

name: Publish Resume

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, curriculum-vitae ]
  pull_request:
    branches: [ master, curriculum-vitae ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: LaTeX Compilation
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@259e5ff953ad4d4616fbd09cc87a526ee5c4499a
        uses: dante-ev/latex-action@latest
        with:
          # The root LaTeX file to be compiled
          root_file: BrianChuResume.tex
          # Extra arguments to be passed to the latex compiler
          compiler: xelatex
          args: -interaction=nonstopmode
          extra_system_packages: fonts-font-awesome
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: get_current_time
        with:
          format: YYYY.MM.DD.HH.mm
          utcOffset: "-8:00"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: BrianChuResume.pdf
          tag: ${{ steps.get_current_time.outputs.formattedTime }}-${{ github.ref }}
          commit: master
          artifactContentType: application/pdf
          
